//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medidea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int IdPatient { get; set; }
        public string FIO { get; set; }
        public string Pol { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
    }
}
