//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medidea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receptions
    {
        public int IdReception { get; set; }
        public Nullable<System.DateTime> DateReception { get; set; }
        public string TypeReception { get; set; }
        public string Diagnosis { get; set; }
    }
}
